In [16]:
import pandas as pd

ff = pd.read_csv("F_N_R_N.csv")
ff

                                                    text  label
0      Gere faults Trump for blurring meaning of 'ref...      1
1      German parties start to find common ground in ...      1
2      Senate Democratic leader says Attorney General...      1
3      Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4       Trump Threw Mar-A-Lago Fundraiser For Woman A...      0
...                                                  ...    ...
45752   Heavily-Armed Man Claiming To Be Jesus Arrest...      0
45753  Evangelicals Across The Spectrum Are Clarifyin...      0
45754  Senators question Kaleo' $4,500 tag on opioid ...      1
45755   CNN Does NOT Hold Back; Completely Makes Fun ...      0
45756  U.S. judge throws out Texas voter ID law suppo...      1

[45757 rows x 2 columns]

In [17]:
ff.head()

                                                text  label
0  Gere faults Trump for blurring meaning of 'ref...      1
1  German parties start to find common ground in ...      1
2  Senate Democratic leader says Attorney General...      1
3  Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4   Trump Threw Mar-A-Lago Fundraiser For Woman A...      0

In [18]:
ff.tail()

                                                    text  label
45752   Heavily-Armed Man Claiming To Be Jesus Arrest...      0
45753  Evangelicals Across The Spectrum Are Clarifyin...      0
45754  Senators question Kaleo' $4,500 tag on opioid ...      1
45755   CNN Does NOT Hold Back; Completely Makes Fun ...      0
45756  U.S. judge throws out Texas voter ID law suppo...      1

In [19]:
ff.shape

(45757, 2)

In [20]:
ff.describe()

              label
count  45757.000000
mean       0.500470
std        0.500005
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000

In [21]:
ff.info()

<class 'pandas.DataFrame'>
RangeIndex: 45757 entries, 0 to 45756
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    45757 non-null  str
 1   label   45757 non-null  int64
dtypes: int64(1), str(1)
memory usage: 715.1 KB

In [22]:
ff.isna().sum().reset_index()

   index  0
0   text  0
1  label  0

In [41]:
ff[("label")].value_counts()

label
1    22900
0    22857
Name: count, dtype: int64

In [38]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = ff["text"]
y = ff["label"]
print(X.shape)
print(y.shape)

(45757,)
(45757,)

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train.shape)
print(X_test.shape)

(36605,)
(9152,)

In [42]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ValueError: could not convert string to float: ' Prisoners Are Going On Strike Across The United States To End Legal Slavery Yesterday marked the 45th anniversary of the Attica prison uprising. The uprising was the first major prison uprising in the United States. Today, there will be a nation-wide prison strike is a modern day slave rebellion.The IWW Incarcerated Workers Organizing Committee put out a call to action, saying: On September 9th of 1971 prisoners took over and shut down Attica, New York State s most notorious prison. On September 9th of 2016, we will begin an action to shut down prisons all across this country. We will not only demand the end to prison slavery, we will end it ourselves by ceasing to be slaves. Work stoppages will occur in prisons across the United States. Organizers on the outside will also be conducting mass demonstrations across the nation.Slavery is legal in the United States of America. That may not be what you were told while growing up but it is completely true and is enshrined in the Constitution. Section 1 of the 13th Amendment states that: Neither slavery nor involuntary servitude, except as a punishment for crime whereof the party shall have been duly convicted, shall exist within the United States, or any place subject to their jurisdiction. When the 13th Amendment was ratified, it did not make slavery illegal. It made it illegal for private entities to own slaves. Once an individual is convicted of a crime, they are slaves until their sentence is served. Despite the illegality of private slavery, corporations are making a killing by using publicly owned slaves. Everything from Victoria s Secret lingerie to juice boxes has been manufactured in slave operated factories, that we refer to prisons.There are more people of color in prison today than there were during the days of private slavery. That is a disturbing fact that must be brought up when speaking on the topic of public slavery.People reading this (or who decided to comment on the article without reading it) might say that prisoners are being taught valuable skills that will help them once they are released from prison. That s absolutely correct. That being said, a skilled person with a criminal record is still a person with a criminal record. We brand our slaves in the United States. Those people would also be in good company of those who defended the practice of chattel slavery in the south prior to the emancipation of private slaves.Those who defended private slavery viewed slave masters as the benefactors of privately owned slaves. People of color were considered to be unskilled and unable to provide for themselves adequately on their own.It is now time that people realize that there is a modern-day abolitionist movement growing in the United States. Incarcerated workers must rise up. Those who are not incarcerated must support them. It s time to join the fight and recognize that slavery did not end when the 13th Amendment was ratified, it decided who was eligible to hold slaves in bondage and who isn t.Those who are incarcerated are risking their lives by fighting back against their owners. They may be beaten, tortured, or otherwise penalized for demanding their basic human rights be recognized.Featured image from Justin Sullivan/Getty Images'